<?php

declare(strict_types=1);

use Lightitlabs\Auth\Frontend\FrontendStubTokens;
use Lightitlabs\Tools\OriginMarker;
use Lightitlabs\Tools\StubRenderer;

// Fixed so the golden fixtures stay stable across CI runs regardless of the
// package's real installed version.
const GOOGLE_SSO_GOLDEN_TEST_MARKER_VERSION = '0.0.0-test';

$fixturePath = static function (string $relative): string {
    return __DIR__.'/../Fixtures/frontend/expected/'.$relative;
};

$stubPath = static function (string $relative): string {
    return __DIR__.'/../../src/Stubs/Frontend/GoogleSSO/'.$relative;
};

describe('GoogleSSO frontend stub rendering', function () use ($fixturePath, $stubPath): void {
    it('renders a stub byte-for-byte against its golden fixture, marker included', function (
        string $stub,
        string $fixture,
    ) use ($fixturePath, $stubPath): void {
        $marker = new OriginMarker(GOOGLE_SSO_GOLDEN_TEST_MARKER_VERSION);

        $rendered = (new StubRenderer)->render($stubPath($stub), FrontendStubTokens::defaults(), $marker);

        expect($rendered)
            ->toBe(file_get_contents($fixturePath($fixture)))
            ->toContain('Generated by the light-it auth package v0.0.0-test (GoogleSSO).');
    })->with([
        ['services/auth/sso/google/types.ts.stub', 'src/services/auth/sso/google/types.ts'],
        ['services/auth/sso/google/schemas.ts.stub', 'src/services/auth/sso/google/schemas.ts'],
        ['services/auth/sso/google/api.ts.stub', 'src/services/auth/sso/google/api.ts'],
        ['services/auth/sso/google/actions.ts.stub', 'src/services/auth/sso/google/actions.ts'],
        ['AUTH-GOOGLE-SSO-FRONTEND-TODO.md.stub', 'AUTH-GOOGLE-SSO-FRONTEND-TODO.md'],
    ]);

    it('leaves no placeholder unresolved in any stub', function () use ($stubPath): void {
        $stubs = glob($stubPath('{,*/,*/*/,*/*/*/,*/*/*/*/}*.stub'), \GLOB_BRACE);
        $renderer = new StubRenderer;

        expect($stubs)->toHaveCount(5);

        foreach ($stubs as $stub) {
            expect($renderer->render($stub, FrontendStubTokens::defaults()))
                ->not->toMatch('/\{\{\s*[a-z][a-zA-Z]*\s*\}\}/');
        }
    });

    it('posts the field named `token`, not `idToken`, matching GoogleLoginRequest::TOKEN', function () use (
        $fixturePath, $stubPath
    ): void {
        $marker = new OriginMarker(GOOGLE_SSO_GOLDEN_TEST_MARKER_VERSION);
        $rendered = (new StubRenderer)->render(
            $stubPath('services/auth/sso/google/api.ts.stub'),
            FrontendStubTokens::defaults(),
            $marker,
        );

        expect($rendered)
            ->toBe(file_get_contents($fixturePath('src/services/auth/sso/google/api.ts')))
            ->toContain('googleSsoApi.post("auth/google", { token: idToken })')
            ->not->toContain('{ idToken })');
    });

    it('does not attach a manual Authorization header, unlike the two-factor exchange endpoints', function () use (
        $fixturePath, $stubPath
    ): void {
        $marker = new OriginMarker(GOOGLE_SSO_GOLDEN_TEST_MARKER_VERSION);
        $rendered = (new StubRenderer)->render(
            $stubPath('services/auth/sso/google/api.ts.stub'),
            FrontendStubTokens::defaults(),
            $marker,
        );

        expect($rendered)
            ->toBe(file_get_contents($fixturePath('src/services/auth/sso/google/api.ts')))
            ->not->toContain('Authorization')
            ->not->toContain('bearer(');
    });

    it('spells the provenance marker so cspell can tokenize it', function () use (
        $fixturePath, $stubPath
    ): void {
        $marker = new OriginMarker(GOOGLE_SSO_GOLDEN_TEST_MARKER_VERSION);
        $rendered = (new StubRenderer)->render(
            $stubPath('AUTH-GOOGLE-SSO-FRONTEND-TODO.md.stub'),
            FrontendStubTokens::defaults(),
            $marker,
        );

        expect($rendered)
            ->toBe(file_get_contents($fixturePath('AUTH-GOOGLE-SSO-FRONTEND-TODO.md')))
            ->toContain('light-it')
            ->not->toContain('lightit');
    });
});
