<?php

declare(strict_types=1);

use Lightitlabs\Auth\Frontend\FrontendStubTokens;
use Lightitlabs\Auth\Frontend\FrontendUsageScanner;
use Lightitlabs\Auth\Permissions\PermissionCatalog;
use Lightitlabs\Tools\OriginMarker;
use Lightitlabs\Tools\StubRenderer;

// Fixed so the golden fixtures stay stable across CI runs regardless of the
// package's real installed version.
const LARAVEL_PERMISSIONS_GOLDEN_TEST_MARKER_VERSION = '0.0.0-test';

$fixturePath = static function (string $relative): string {
    return __DIR__.'/../Fixtures/frontend/expected/'.$relative;
};

$stubPath = static function (string $relative): string {
    return __DIR__.'/../../src/Stubs/Frontend/LaravelPermissions/'.$relative;
};

$reactProject = __DIR__.'/../Fixtures/frontend/react-project';

$realTokens = static function () use ($reactProject): array {
    $catalog = new PermissionCatalog;
    $scanner = new FrontendUsageScanner;

    return [
        ...FrontendStubTokens::defaults(),
        'permissionConstants' => $catalog->toTypeScriptConstants(),
        'permissionCallSites' => $scanner->toMarkdownList(
            $scanner->grep($reactProject, '/\bhasPermission\(/')
        ),
        'currentUserQueryProbeNote' => 'No `src/services/auth/factories.ts` was found at the resolved '
            .'frontend root - the import above is a best guess. Repoint `currentUserQueryImportPath` in '
            .'both files above to wherever your current-user query factory actually lives.',
    ];
};

describe('LaravelPermission frontend stub rendering', function () use ($fixturePath, $stubPath, $realTokens): void {
    it('renders a stub byte-for-byte against its golden fixture, marker included', function (
        string $stub,
        string $fixture,
    ) use ($fixturePath, $stubPath, $realTokens): void {
        $marker = new OriginMarker(LARAVEL_PERMISSIONS_GOLDEN_TEST_MARKER_VERSION);

        $rendered = (new StubRenderer)->render($stubPath($stub), $realTokens(), $marker);

        expect($rendered)
            ->toBe(file_get_contents($fixturePath($fixture)))
            ->toContain('Generated by the light-it auth package v0.0.0-test (LaravelPermissions).');
    })->with([
        ['services/permissions/constants.ts.stub', 'src/services/permissions/constants.ts'],
        ['services/permissions/use-permissions.ts.stub', 'src/services/permissions/use-permissions.ts'],
        ['services/permissions/ensure-permission.ts.stub', 'src/services/permissions/ensure-permission.ts'],
        ['ROLES-PERMISSIONS-FRONTEND-TODO.md.stub', 'ROLES-PERMISSIONS-FRONTEND-TODO.md'],
    ]);

    it('leaves no placeholder unresolved in any stub', function () use ($stubPath): void {
        $stubs = glob($stubPath('{,*/,*/*/,*/*/*/}*.stub'), \GLOB_BRACE);
        $renderer = new StubRenderer;

        expect($stubs)->toHaveCount(4);

        foreach ($stubs as $stub) {
            expect($renderer->render($stub, FrontendStubTokens::defaults()))
                ->not->toMatch('/\{\{\s*[a-z][a-zA-Z]*\s*\}\}/');
        }
    });

    it('generates the PermissionValue union from PermissionCatalog, not a hand-maintained list', function () use (
        $fixturePath
    ): void {
        $constants = file_get_contents($fixturePath('src/services/permissions/constants.ts'));

        foreach (array_keys(PermissionCatalog::entries()) as $permissionName) {
            expect($constants)->toContain("'{$permissionName}',");
        }
    });

    it('generates exactly one guard and no PermissionGate component', function () use ($fixturePath): void {
        $ensurePermission = file_get_contents($fixturePath('src/services/permissions/ensure-permission.ts'));
        $usePermissions = file_get_contents($fixturePath('src/services/permissions/use-permissions.ts'));
        $todo = file_get_contents($fixturePath('ROLES-PERMISSIONS-FRONTEND-TODO.md'));

        expect($ensurePermission)->toContain('export const ensurePermission =');
        expect($usePermissions)->not->toContain('PermissionGate');
        expect($ensurePermission)->not->toContain('PermissionGate');
        expect($todo)
            ->toContain('The one guard')
            ->toContain('No `<PermissionGate>` component is generated');
    });

    it('surfaces existing inline permission checks as a migration list', function () use ($fixturePath): void {
        expect(file_get_contents($fixturePath('ROLES-PERMISSIONS-FRONTEND-TODO.md')))
            ->toContain('- `src/routes/manage-roles.tsx:2`');
    });

    it('points back to the backend TODO for patch-status, Gate::before and HasRoles info', function () use (
        $fixturePath
    ): void {
        expect(file_get_contents($fixturePath('ROLES-PERMISSIONS-FRONTEND-TODO.md')))
            ->toContain('ROLES-PERMISSIONS-TODO.md');
    });
});
