// Generated by the light-it auth package v0.0.0-test (Passkeys).

import axios from "axios";
import { deepCamelKeys } from "string-ts";

import { env } from "@/config/env";
import type {
  Passkey,
  PasskeyCeremonyError,
  PasskeyCeremonyErrorReason,
  PasskeyCreationOptions,
  PasskeyLoginResult,
  PasskeyRequestOptions,
} from "./types";

const passkeysApi = axios.create({
  baseURL: env.VITE_API_URL,
  headers: {
    "Content-Type": "application/json",
    Accept: "application/json",
  },
});

passkeysApi.interceptors.response.use((response) => {
  response.data = deepCamelKeys(response.data);

  return response;
});

// The registration and login options responses echo the browser's own
// WebAuthn JSON casing back unmodified - deepCamelKeys would corrupt it, so
// this instance carries no response interceptor at all.
const passkeysCeremonyApi = axios.create({
  baseURL: env.VITE_API_URL,
  headers: {
    "Content-Type": "application/json",
    Accept: "application/json",
  },
});

const bearer = (token: string) => {
  return { headers: { Authorization: `Bearer ${token}` } };
};

export const getPasskeyRegistrationOptions = async ({
  token,
}: {
  token: string;
}): Promise<PasskeyCreationOptions> => {
  const response = await passkeysCeremonyApi.post(
    "passkeys/registration-options",
    undefined,
    bearer(token),
  );

  return response.data.data;
};

export const createPasskey = async ({
  token,
  name,
  credential,
}: {
  token: string;
  name: string;
  credential: PublicKeyCredentialJSON;
}): Promise<Passkey> => {
  const response = await passkeysApi.post("passkeys", { name, credential }, bearer(token));

  return response.data.data;
};

export const listPasskeys = async ({ token }: { token: string }): Promise<Passkey[]> => {
  const response = await passkeysApi.get("passkeys", bearer(token));

  return response.data.data;
};

export const deletePasskey = async ({ token, id }: { token: string; id: number }): Promise<void> => {
  await passkeysApi.delete(`passkeys/${id}`, bearer(token));
};

export const getPasskeyLoginOptions = async (): Promise<PasskeyRequestOptions> => {
  const response = await passkeysCeremonyApi.post("auth/passkey/options");

  // Only the wrapper key is this package's own naming choice - `public_key`'s
  // contents are the browser's WebAuthn JSON and are passed through untouched.
  const data = response.data.data as {
    ceremony_id: string;
    public_key: PublicKeyCredentialRequestOptionsJSON;
  };

  return { ceremonyId: data.ceremony_id, publicKey: data.public_key };
};

export const loginWithPasskey = async ({
  ceremonyId,
  credential,
}: {
  ceremonyId: string;
  credential: PublicKeyCredentialJSON;
}): Promise<PasskeyLoginResult> => {
  const response = await passkeysApi.post("auth/passkey", {
    ceremony_id: ceremonyId,
    credential,
  });

  return response.data.data;
};

export const createPasskeyCredential = async (
  options: PasskeyCreationOptions,
): Promise<PublicKeyCredentialJSON> => {
  const credential = await navigator.credentials.create({
    publicKey: PublicKeyCredential.parseCreationOptionsFromJSON(options),
  });

  if (!(credential instanceof PublicKeyCredential)) {
    throw new Error("navigator.credentials.create() returned no credential.");
  }

  return credential.toJSON();
};

export const getPasskeyCredential = async (
  options: PasskeyRequestOptions,
): Promise<PublicKeyCredentialJSON> => {
  const credential = await navigator.credentials.get({
    publicKey: PublicKeyCredential.parseRequestOptionsFromJSON(options.publicKey),
  });

  if (!(credential instanceof PublicKeyCredential)) {
    throw new Error("navigator.credentials.get() returned no credential.");
  }

  return credential.toJSON();
};

// DOMException.name is the only signal the browser gives back for a failed
// ceremony: InvalidStateError means an authenticator already holds a passkey
// for this site (the excludeCredentials list working as designed),
// NotAllowedError covers both a user cancellation and a timeout under the same
// name, and SecurityError means the RP ID does not match the origin (see the
// config's relying_party.id comment) - surfaced verbatim rather than guessed at.
export const mapPasskeyCeremonyError = (error: unknown): PasskeyCeremonyError => {
  if (error instanceof DOMException) {
    const reason: PasskeyCeremonyErrorReason = ((): PasskeyCeremonyErrorReason => {
      switch (error.name) {
        case "InvalidStateError":
          return "already_registered";
        case "NotAllowedError":
          return "cancelled_or_timed_out";
        case "SecurityError":
          return "security_error";
        default:
          return "unknown";
      }
    })();

    return { reason, domExceptionName: error.name, message: error.message };
  }

  return {
    reason: "unknown",
    domExceptionName: null,
    message: error instanceof Error ? error.message : "Unknown passkey ceremony error.",
  };
};
