// Generated by the light-it auth package v0.0.0-test (SanctumCookie).

import { z } from "zod";

import i18n from "@/i18n";

export const getLoginPayloadSchema = () => {
  return z.object({
    email: z.string().email({
      message: i18n.t("form.errors.invalidField", { field: i18n.t("form.email") }),
    }),
    password: z.string().min(6, {
      message: i18n.t("form.errors.minLength", { field: i18n.t("form.password"), length: 6 }),
    }),
  });
};
