// Generated by the light-it auth package v0.0.0-test (SanctumCookie).

import type { z } from "zod";

import type { getLoginPayloadSchema } from "./schemas";

export type LoginPayload = z.infer<ReturnType<typeof getLoginPayloadSchema>>;
