<?php

declare(strict_types=1);

use Illuminate\Console\Command;
use Lightitlabs\Auth\Installers\ComposerInstaller;
use Lightitlabs\Auth\Installers\Google2FAInstaller;
use Lightitlabs\Auth\Installers\SanctumInstaller;
use Lightitlabs\Tools\OriginMarker;
use Lightitlabs\Tools\StubCopier;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\NullOutput;

/**
 * SanctumInstaller and Google2FAInstaller both write
 * src/Authentication/Domain/Actions/LoginAction.php. In an ordinary "Password
 * + 2FA" install, AuthSetupCommand::handle() runs login methods (Sanctum)
 * before features (2FA), so Sanctum's plain LoginAction.php exists by the
 * time Google2FAInstaller runs - it must replace it with the 2FA pipeline
 * version rather than skip it, but only while it still looks untouched. See
 * LoginActionPatcher.
 */
function runCreateAuthFiles(object $installer): void
{
    $createAuthFiles = new ReflectionMethod($installer, 'createAuthFiles');
    $createAuthFiles->setAccessible(true);
    $createAuthFiles->invoke($installer);
}

describe('LoginAction.php collision between SanctumInstaller and Google2FAInstaller', function (): void {
    beforeEach(function (): void {
        $this->tempBase = sys_get_temp_dir().'/login-action-collision-'.uniqid();
        mkdir($this->tempBase, 0755, true);
        $this->originalBasePath = $this->app->basePath();
        $this->app->setBasePath($this->tempBase);
        $this->destination = $this->tempBase.'/src/Authentication/Domain/Actions/LoginAction.php';
    });

    afterEach(function (): void {
        $this->app->setBasePath($this->originalBasePath);

        $files = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($this->tempBase, FilesystemIterator::SKIP_DOTS),
            RecursiveIteratorIterator::CHILD_FIRST
        );

        foreach ($files as $file) {
            $file->isDir() ? rmdir($file->getPathname()) : unlink($file->getPathname());
        }

        rmdir($this->tempBase);
    });

    it('installs the 2FA LoginAction, not Sanctum\'s, on an ordinary Password + 2FA install', function (): void {
        $command = new class extends Command
        {
            protected $signature = 'login-action-collision-test';

            public function handle(): int
            {
                $composerInstaller = new ComposerInstaller($this);
                $stubCopier = new StubCopier(new OriginMarker('0.0.0-test'));

                // Mirrors AuthSetupCommand::setupSanctum() then ::setup2FA():
                // login methods are installed before features.
                $sanctum = new SanctumInstaller($this, $composerInstaller, $stubCopier);
                runCreateAuthFiles($sanctum);

                $google2fa = new Google2FAInstaller($this, $composerInstaller, $stubCopier);
                runCreateAuthFiles($google2fa);

                return self::SUCCESS;
            }
        };

        $command->setLaravel($this->app);
        $command->run(new ArrayInput([]), new NullOutput);

        $expected2FaStub = (string) file_get_contents(
            __DIR__.'/../../../../src/Stubs/Google2FA/Auth/Actions/LoginAction.stub'
        );
        $expectedContent = str_replace(
            "<?php\n\n",
            "<?php\n\n// Generated by the light-it auth package v0.0.0-test (Google2FA).\n\n",
            $expected2FaStub
        );

        expect((string) file_get_contents($this->destination))->toBe($expectedContent);
    });

    it('does not overwrite a LoginAction.php a consumer edited after Sanctum installed it', function (): void {
        $command = new class extends Command
        {
            protected $signature = 'login-action-collision-preserve-test';

            public function handle(): int
            {
                $composerInstaller = new ComposerInstaller($this);
                $stubCopier = new StubCopier(new OriginMarker('0.0.0-test'));

                $sanctum = new SanctumInstaller($this, $composerInstaller, $stubCopier);
                runCreateAuthFiles($sanctum);

                $target = base_path('src/Authentication/Domain/Actions/LoginAction.php');
                file_put_contents($target, '// customized by the consuming project'.PHP_EOL);

                $google2fa = new Google2FAInstaller($this, $composerInstaller, $stubCopier);
                runCreateAuthFiles($google2fa);

                return self::SUCCESS;
            }
        };

        $command->setLaravel($this->app);
        $command->run(new ArrayInput([]), new NullOutput);

        expect((string) file_get_contents($this->destination))->toBe('// customized by the consuming project'.PHP_EOL);
    });

    it('is idempotent when 2FA install runs twice', function (): void {
        $command = new class extends Command
        {
            protected $signature = 'login-action-collision-idempotency-test';

            public function handle(): int
            {
                $composerInstaller = new ComposerInstaller($this);
                $stubCopier = new StubCopier(new OriginMarker('0.0.0-test'));

                $sanctum = new SanctumInstaller($this, $composerInstaller, $stubCopier);
                runCreateAuthFiles($sanctum);

                $google2fa = new Google2FAInstaller($this, $composerInstaller, $stubCopier);
                runCreateAuthFiles($google2fa);
                runCreateAuthFiles($google2fa);

                return self::SUCCESS;
            }
        };

        $command->setLaravel($this->app);
        $command->run(new ArrayInput([]), new NullOutput);

        $content = (string) file_get_contents($this->destination);

        expect(substr_count($content, 'Generated by the light-it auth package'))->toBe(1);
    });
});
