<?php

declare(strict_types=1);

use Illuminate\Console\Command;
use Lightitlabs\Auth\Installers\ComposerInstaller;
use Lightitlabs\Auth\Installers\Google2FAInstaller;
use Lightitlabs\Auth\Installers\SanctumInstaller;
use Lightitlabs\Tools\OriginMarker;
use Lightitlabs\Tools\StubCopier;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\NullOutput;

/**
 * SanctumInstaller and Google2FAInstaller both write to
 * src/Authentication/Domain/Actions/LoginAction.php. In an ordinary
 * "Password + 2FA" install, AuthSetupCommand::handle() runs login methods
 * (Sanctum) before features (2FA), so Sanctum's plain LoginAction.php exists
 * by the time Google2FAInstaller runs. The write guard must tell "this file
 * is ours, written moments ago by a sibling installer" apart from "a
 * consumer edited this file" - overwriting only the former.
 */
function runCreateAuthFiles(object $installer): void
{
    $createAuthFiles = new ReflectionMethod($installer, 'createAuthFiles');
    $createAuthFiles->setAccessible(true);
    $createAuthFiles->invoke($installer);
}

describe('LoginAction.php collision between SanctumInstaller and Google2FAInstaller', function (): void {
    beforeEach(function (): void {
        $this->tempBase = sys_get_temp_dir().'/login-action-collision-'.uniqid();
        mkdir($this->tempBase, 0755, true);
        $this->originalBasePath = $this->app->basePath();
        $this->app->setBasePath($this->tempBase);
        $this->destination = $this->tempBase.'/src/Authentication/Domain/Actions/LoginAction.php';
    });

    afterEach(function (): void {
        $this->app->setBasePath($this->originalBasePath);

        $files = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($this->tempBase, FilesystemIterator::SKIP_DOTS),
            RecursiveIteratorIterator::CHILD_FIRST
        );

        foreach ($files as $file) {
            $file->isDir() ? rmdir($file->getPathname()) : unlink($file->getPathname());
        }

        rmdir($this->tempBase);
    });

    it('installs the 2FA LoginAction, not Sanctum\'s, on an ordinary Password + 2FA install', function (): void {
        $command = new class extends Command
        {
            protected $signature = 'login-action-collision-test';

            public function handle(): int
            {
                $composerInstaller = new ComposerInstaller($this);

                // Mirrors AuthSetupCommand::setupSanctum() then ::setup2FA():
                // login methods are installed before features, and both
                // share the same StubCopier for the whole run - see
                // AuthSetupCommand::stubCopier().
                $stubCopier = new StubCopier(new OriginMarker('0.0.0-test'));

                $sanctum = new SanctumInstaller($this, $composerInstaller, $stubCopier);
                runCreateAuthFiles($sanctum);

                $google2fa = new Google2FAInstaller($this, $composerInstaller, $stubCopier);
                runCreateAuthFiles($google2fa);

                return self::SUCCESS;
            }
        };

        $command->setLaravel($this->app);
        $command->run(new ArrayInput([]), new NullOutput);

        $expected2FaStub = (string) file_get_contents(
            __DIR__.'/../../../../src/Stubs/Google2FA/Auth/Actions/LoginAction.stub'
        );
        $expectedContent = str_replace(
            "<?php\n\n",
            "<?php\n\n// Generated by the light-it auth package v0.0.0-test (Google2FA).\n\n",
            $expected2FaStub
        );

        expect((string) file_get_contents($this->destination))->toBe($expectedContent);
    });

    it('does not overwrite a LoginAction.php a consumer edited after Sanctum installed it', function (): void {
        $command = new class extends Command
        {
            protected $signature = 'login-action-collision-preserve-test';

            public function handle(): int
            {
                $composerInstaller = new ComposerInstaller($this);

                $sanctum = new SanctumInstaller(
                    $this,
                    $composerInstaller,
                    new StubCopier(new OriginMarker('0.0.0-test')),
                );
                runCreateAuthFiles($sanctum);

                return self::SUCCESS;
            }
        };

        $command->setLaravel($this->app);
        $command->run(new ArrayInput([]), new NullOutput);

        // The consumer edits the body of the package-generated file but leaves
        // the origin marker comment untouched - a realistic edit, since devs
        // rarely touch a leading header comment when customizing the body below.
        $generated = (string) file_get_contents($this->destination);
        $edited = str_replace(
            'throw new UnauthenticatedException();',
            "throw new UnauthenticatedException('Custom message added by the consuming team.');",
            $generated
        );
        expect($edited)->not->toBe($generated);
        file_put_contents($this->destination, $edited);

        $command2 = new class extends Command
        {
            protected $signature = 'login-action-collision-preserve-test-2fa';

            public function handle(): int
            {
                $composerInstaller = new ComposerInstaller($this);

                $google2fa = new Google2FAInstaller(
                    $this,
                    $composerInstaller,
                    new StubCopier(new OriginMarker('0.0.0-test')),
                );
                runCreateAuthFiles($google2fa);

                return self::SUCCESS;
            }
        };

        $command2->setLaravel($this->app);
        $command2->run(new ArrayInput([]), new NullOutput);

        expect((string) file_get_contents($this->destination))->toBe($edited);
    });

    it('still refuses to touch a LoginAction.php with no origin marker at all', function (): void {
        if (! is_dir(dirname($this->destination))) {
            mkdir(dirname($this->destination), 0755, true);
        }
        file_put_contents($this->destination, '// hand-written by the consuming project'.PHP_EOL);

        $command = new class extends Command
        {
            protected $signature = 'login-action-collision-foreign-test';

            public function handle(): int
            {
                $composerInstaller = new ComposerInstaller($this);

                $google2fa = new Google2FAInstaller(
                    $this,
                    $composerInstaller,
                    new StubCopier(new OriginMarker('0.0.0-test')),
                );
                runCreateAuthFiles($google2fa);

                return self::SUCCESS;
            }
        };

        $command->setLaravel($this->app);
        $command->run(new ArrayInput([]), new NullOutput);

        expect((string) file_get_contents($this->destination))
            ->toBe('// hand-written by the consuming project'.PHP_EOL);
    });
});
