<?php

declare(strict_types=1);

use Illuminate\Console\Command;
use Lightitlabs\Auth\Installers\ComposerInstaller;
use Lightitlabs\Auth\Installers\SanctumInstaller;
use Lightitlabs\Tools\OriginMarker;
use Lightitlabs\Tools\StubCopier;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\NullOutput;

describe('SanctumInstaller idempotency', function (): void {
    beforeEach(function (): void {
        $this->tempBase = sys_get_temp_dir().'/sanctum-installer-'.uniqid();
        mkdir($this->tempBase, 0755, true);
        $this->originalBasePath = $this->app->basePath();
        $this->app->setBasePath($this->tempBase);
    });

    afterEach(function (): void {
        $this->app->setBasePath($this->originalBasePath);

        $files = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($this->tempBase, FilesystemIterator::SKIP_DOTS),
            RecursiveIteratorIterator::CHILD_FIRST
        );

        foreach ($files as $file) {
            $file->isDir() ? rmdir($file->getPathname()) : unlink($file->getPathname());
        }

        rmdir($this->tempBase);
    });

    it('does not stack a duplicate origin marker when the copy path runs twice', function (): void {
        // SanctumInstaller::install() also calls `install:api`, an artisan command
        // this package's own test app doesn't register (Sanctum isn't a dependency
        // here). Exercising createAuthFiles() directly targets the copy path this
        // feature actually changed, without needing to fake that unrelated command.
        $command = new class extends Command
        {
            protected $signature = 'sanctum-idempotency-test';

            public function handle(): int
            {
                $composerInstaller = new ComposerInstaller($this);
                $stubCopier = new StubCopier(new OriginMarker('0.0.0-test'));
                $installer = new SanctumInstaller($this, $composerInstaller, $stubCopier);

                $createAuthFiles = new ReflectionMethod($installer, 'createAuthFiles');
                $createAuthFiles->setAccessible(true);

                $createAuthFiles->invoke($installer);
                $createAuthFiles->invoke($installer);

                return self::SUCCESS;
            }
        };

        $command->setLaravel($this->app);
        $command->run(new ArrayInput([]), new NullOutput);

        $content = (string) file_get_contents(
            $this->tempBase.'/src/Authentication/App/Requests/LoginRequest.php'
        );

        expect(substr_count($content, 'Generated by the light-it auth package'))->toBe(1)
            ->and($content)->toContain('Generated by the light-it auth package v0.0.0-test (Sanctum).');
    });

    it('does not overwrite an already-generated auth file on a second install', function (): void {
        $command = new class extends Command
        {
            protected $signature = 'sanctum-overwrite-test';

            public function handle(): int
            {
                $composerInstaller = new ComposerInstaller($this);

                // Simulates a second, later `auth:setup` run - a fresh process with its
                // own StubCopier, not a second call reusing the first run's instance.
                // See StubCopier::wasWrittenThisRun(): only a write from *this* run may
                // be replaced without an exists check.
                $firstRunInstaller = new SanctumInstaller(
                    $this,
                    $composerInstaller,
                    new StubCopier(new OriginMarker('0.0.0-test')),
                );

                $createAuthFiles = new ReflectionMethod($firstRunInstaller, 'createAuthFiles');
                $createAuthFiles->setAccessible(true);
                $createAuthFiles->invoke($firstRunInstaller);

                $target = base_path('src/Authentication/App/Requests/LoginRequest.php');
                file_put_contents($target, '// customized by the consuming project'.PHP_EOL);

                $secondRunInstaller = new SanctumInstaller(
                    $this,
                    $composerInstaller,
                    new StubCopier(new OriginMarker('0.0.0-test')),
                );
                $createAuthFiles->invoke($secondRunInstaller);

                return self::SUCCESS;
            }
        };

        $command->setLaravel($this->app);
        $command->run(new ArrayInput([]), new NullOutput);

        $content = (string) file_get_contents(
            $this->tempBase.'/src/Authentication/App/Requests/LoginRequest.php'
        );

        expect($content)->toBe('// customized by the consuming project'.PHP_EOL);
    });
});
