<?php

declare(strict_types=1);

use Illuminate\Console\Command;
use Illuminate\Foundation\Application;
use Lightitlabs\Auth\Installers\ComposerInstaller;
use Lightitlabs\Auth\Installers\GoogleSSOInstaller;
use Lightitlabs\Tools\FileManipulator;
use Lightitlabs\Tools\OriginMarker;
use Lightitlabs\Tools\StubCopier;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\NullOutput;

/**
 * Exercises `GoogleSSOInstaller::registerRoutes()` / `registerServiceProvider()` directly
 * via reflection, without going through `install()` (which also runs a real `composer
 * require` for `google/apiclient`, outside the scope of this feature).
 */
function runGoogleSsoInstallerStep(Command $command, string $method): void
{
    $composerInstaller = new ComposerInstaller($command);
    $stubCopier = new StubCopier(new OriginMarker('0.0.0-test'));
    $fileManipulator = new FileManipulator($command);
    $installer = new GoogleSSOInstaller($command, $composerInstaller, $stubCopier, $fileManipulator);

    $reflection = new ReflectionMethod($installer, $method);
    $reflection->setAccessible(true);
    $reflection->invoke($installer);
}

/**
 * Mirrors `StubCopier::copy()`'s own origin-marker injection, so full-file assertions can
 * compare the copied output against the source stub without a `toContain()` fragment check.
 */
function googleSsoStubWithOriginMarker(string $stubPath): string
{
    $contents = (string) file_get_contents($stubPath);
    $header = "<?php\n\n";
    $marker = 'Generated by the light-it auth package v0.0.0-test (GoogleSSO).';

    return str_starts_with($contents, $header)
        ? $header."// {$marker}\n\n".substr($contents, strlen($header))
        : "// {$marker}\n".$contents;
}

function fakeGoogleSsoCommand(Application $app, string $signature): Command
{
    $command = new class extends Command
    {
        protected $signature = 'google-sso-fake';

        public function handle(): int
        {
            return self::SUCCESS;
        }
    };
    $command->setName($signature);
    $command->setLaravel($app);
    $command->run(new ArrayInput([]), new NullOutput);

    return $command;
}

describe('GoogleSSOInstaller route and service provider registration', function (): void {
    beforeEach(function (): void {
        $this->tempBase = sys_get_temp_dir().'/google-sso-installer-'.uniqid();
        mkdir($this->tempBase.'/routes', 0755, true);
        mkdir($this->tempBase.'/bootstrap', 0755, true);
        $this->originalBasePath = $this->app->basePath();
        $this->app->setBasePath($this->tempBase);
    });

    afterEach(function (): void {
        $this->app->setBasePath($this->originalBasePath);

        $files = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($this->tempBase, FilesystemIterator::SKIP_DOTS),
            RecursiveIteratorIterator::CHILD_FIRST
        );

        foreach ($files as $file) {
            $file->isDir() ? rmdir($file->getPathname()) : unlink($file->getPathname());
        }

        rmdir($this->tempBase);
    });

    describe('registerRoutes()', function (): void {
        it('writes the google-sso routes stub and registers a require line in routes/api.php', function (): void {
            file_put_contents($this->tempBase.'/routes/api.php', "<?php\n\ndeclare(strict_types=1);\n");

            runGoogleSsoInstallerStep(fakeGoogleSsoCommand($this->app, 'google-sso-routes-test'), 'registerRoutes');

            expect(file_get_contents($this->tempBase.'/routes/google-sso.php'))
                ->toBe(googleSsoStubWithOriginMarker(__DIR__.'/../../src/Stubs/GoogleSSO/routes/google-sso.stub'));

            expect(file_get_contents($this->tempBase.'/routes/api.php'))->toBe(
                "<?php\n\ndeclare(strict_types=1);\n\n"
                ."// lightit-auth: google sso routes\n"
                ."require __DIR__.'/google-sso.php';\n"
            );
        });

        it('does not duplicate the require line or overwrite the routes stub on a second run', function (): void {
            file_put_contents($this->tempBase.'/routes/api.php', "<?php\n\ndeclare(strict_types=1);\n");
            $command = fakeGoogleSsoCommand($this->app, 'google-sso-routes-idempotent-test');

            runGoogleSsoInstallerStep($command, 'registerRoutes');
            $firstRoutesStub = file_get_contents($this->tempBase.'/routes/google-sso.php');
            $firstApiRoutes = file_get_contents($this->tempBase.'/routes/api.php');

            runGoogleSsoInstallerStep($command, 'registerRoutes');

            expect(file_get_contents($this->tempBase.'/routes/google-sso.php'))->toBe($firstRoutesStub)
                ->and(file_get_contents($this->tempBase.'/routes/api.php'))->toBe($firstApiRoutes)
                ->and(substr_count((string) $firstApiRoutes, 'lightit-auth: google sso routes'))->toBe(1);
        });

        it('still writes the routes stub when routes/api.php does not exist', function (): void {
            runGoogleSsoInstallerStep(
                fakeGoogleSsoCommand($this->app, 'google-sso-routes-no-parent-test'),
                'registerRoutes'
            );

            expect(file_get_contents($this->tempBase.'/routes/google-sso.php'))
                ->toBe(googleSsoStubWithOriginMarker(__DIR__.'/../../src/Stubs/GoogleSSO/routes/google-sso.stub'));
        });
    });

    describe('registerServiceProvider()', function (): void {
        beforeEach(function (): void {
            file_put_contents(
                $this->tempBase.'/bootstrap/providers.php',
                "<?php\n\nreturn [\n    App\\Providers\\AppServiceProvider::class,\n];\n"
            );
        });

        it('copies the config and service provider files, and registers the provider', function (): void {
            runGoogleSsoInstallerStep(
                fakeGoogleSsoCommand($this->app, 'google-sso-service-provider-test'),
                'registerServiceProvider'
            );

            expect(file_get_contents($this->tempBase.'/config/google-sso.php'))
                ->toBe(googleSsoStubWithOriginMarker(__DIR__.'/../../src/Stubs/GoogleSSO/config/google-sso.stub'));

            expect(file_get_contents($this->tempBase.'/app/Providers/GoogleClientServiceProvider.php'))
                ->toBe(googleSsoStubWithOriginMarker(
                    __DIR__.'/../../src/Stubs/GoogleSSO/Providers/GoogleClientServiceProvider.stub'
                ));

            expect(file_get_contents($this->tempBase.'/bootstrap/providers.php'))->toBe(
                "<?php\n\nreturn [\n"
                ."    \\App\\Providers\\GoogleClientServiceProvider::class,\n"
                ."    App\\Providers\\AppServiceProvider::class,\n];\n"
            );
        });

        it('does not duplicate the provider registration on a second run', function (): void {
            $command = fakeGoogleSsoCommand($this->app, 'google-sso-service-provider-idempotent-test');

            runGoogleSsoInstallerStep($command, 'registerServiceProvider');
            $firstProviders = file_get_contents($this->tempBase.'/bootstrap/providers.php');

            runGoogleSsoInstallerStep($command, 'registerServiceProvider');

            expect(file_get_contents($this->tempBase.'/bootstrap/providers.php'))->toBe($firstProviders)
                ->and(substr_count((string) $firstProviders, 'GoogleClientServiceProvider::class'))->toBe(1);
        });

        it('does not overwrite a customized config or service provider file on a second run', function (): void {
            $command = fakeGoogleSsoCommand($this->app, 'google-sso-service-provider-no-clobber-test');

            runGoogleSsoInstallerStep($command, 'registerServiceProvider');

            $customizedConfig = "<?php\n\nreturn ['client_id' => 'customized'];\n";
            $customizedProvider = "<?php\n\n// customized by the consumer\n";
            file_put_contents($this->tempBase.'/config/google-sso.php', $customizedConfig);
            file_put_contents($this->tempBase.'/app/Providers/GoogleClientServiceProvider.php', $customizedProvider);

            runGoogleSsoInstallerStep($command, 'registerServiceProvider');

            expect(file_get_contents($this->tempBase.'/config/google-sso.php'))->toBe($customizedConfig)
                ->and(file_get_contents($this->tempBase.'/app/Providers/GoogleClientServiceProvider.php'))
                ->toBe($customizedProvider);
        });

        it('leaves bootstrap/providers.php untouched and warns instead of claiming success when it has no `return [` anchor', function (): void {
            file_put_contents(
                $this->tempBase.'/bootstrap/providers.php',
                "<?php\n\nreturn array(\n    App\\Providers\\AppServiceProvider::class,\n);\n"
            );

            runGoogleSsoInstallerStep(
                fakeGoogleSsoCommand($this->app, 'google-sso-service-provider-no-anchor-test'),
                'registerServiceProvider'
            );

            expect(file_get_contents($this->tempBase.'/bootstrap/providers.php'))->toBe(
                "<?php\n\nreturn array(\n    App\\Providers\\AppServiceProvider::class,\n);\n"
            );
        });

        it('still copies the config and provider files when bootstrap/providers.php does not exist', function (): void {
            unlink($this->tempBase.'/bootstrap/providers.php');

            runGoogleSsoInstallerStep(
                fakeGoogleSsoCommand($this->app, 'google-sso-service-provider-no-target-test'),
                'registerServiceProvider'
            );

            expect(file_get_contents($this->tempBase.'/config/google-sso.php'))
                ->toBe(googleSsoStubWithOriginMarker(__DIR__.'/../../src/Stubs/GoogleSSO/config/google-sso.stub'));
            expect(file_exists($this->tempBase.'/bootstrap/providers.php'))->toBeFalse();
        });
    });
});
