<?php

declare(strict_types=1);

use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\File;
use Lightitlabs\Auth\Frontend\FrontendPackageManifest;
use Lightitlabs\Auth\Frontend\FrontendProjectLocator;
use Lightitlabs\Auth\Installers\SocialLoginFrontendInstaller;
use Lightitlabs\Tools\StubRenderer;

describe('SocialLoginFrontendInstaller', function (): void {
    beforeEach(function (): void {
        $this->root = sys_get_temp_dir() . '/lightit-social-frontend-' . bin2hex(random_bytes(6));
        File::copyDirectory(__DIR__ . '/../Fixtures/frontend/react-project', $this->root);

        $this->sourceFiles = [
            'src/services/auth/social/types.ts',
            'src/services/auth/social/api.ts',
            'src/services/auth/social/google-identity.ts',
            'src/routes/(public)/_guest/login/-components/google-login-button.tsx',
            'src/routes/(public)/_guest/login/-hooks/use-sign-in-with-google.ts',
        ];

        $root = $this->root;
        Artisan::command('social-frontend-fake', function () use ($root): void {
            $manifest = new FrontendPackageManifest();

            (new SocialLoginFrontendInstaller(
                $this,
                new StubRenderer(),
                new FrontendProjectLocator($manifest),
                $manifest,
                sys_get_temp_dir() . '/lightit-social-laravel-root',
                $root,
            ))->install();
        });

        $this->documentedKeys = function (): array {
            preg_match(
                '/```json\n(.*?)```/s',
                (string) file_get_contents($this->root . '/AUTH-SOCIAL-FRONTEND-TODO.md'),
                $block
            );

            return json_decode('{' . $block[1] . '}', true, flags: JSON_THROW_ON_ERROR);
        };
    });

    afterEach(function (): void {
        File::deleteDirectory($this->root);
    });

    it(
        'writes the social services, the Google button, its hook and the TODO with every placeholder resolved',
        function (): void {
            $this->artisan('social-frontend-fake')->assertSuccessful();

            foreach ([...$this->sourceFiles, 'AUTH-SOCIAL-FRONTEND-TODO.md'] as $relative) {
                expect($this->root . '/' . $relative)->toBeFile()
                    ->and(file_get_contents($this->root . '/' . $relative))->not->toMatch('/\{\{\s*[a-zA-Z]+\s*\}\}/');
            }
        }
    );

    it('writes the TODO as a short checklist that says to delete it when done', function (): void {
        $this->artisan('social-frontend-fake')->assertSuccessful();

        expect(file_get_contents($this->root . '/AUTH-SOCIAL-FRONTEND-TODO.md'))
            ->toStartWith("# Social login setup checklist (frontend)\n\n> Generated by `php artisan auth:setup")
            ->toContain('then **delete this file**')
            ->toContain('`docs/social-login.md`')
            ->toContain("\n- [ ] **Install dependencies** (`pnpm`): ")
            ->toContain("\n- [ ] **Set the Google client id**")
            ->toContain(
                "\n- [ ] **Add the \"Sign in with Google\" button** in `src/routes/(public)/_guest/login/-components/login-form.tsx`"
            )
            ->toContain("\n- [ ] **Add the i18n keys**")
            ->toContain('Check it worked: ')
            ->not->toContain('lightit');
    });

    it('reports Skipped on a second run and never touches a file the app already has', function (): void {
        mkdir($this->root . '/src/services/auth/social', 0755, true);
        file_put_contents($this->root . '/src/services/auth/social/api.ts', 'export {};' . PHP_EOL);

        $this->artisan('social-frontend-fake')
            ->expectsOutputToContain('Skipped src/services/auth/social/api.ts')
            ->assertSuccessful();

        $before = file_get_contents(
            $this->root . '/src/routes/(public)/_guest/login/-components/google-login-button.tsx'
        );

        $this->artisan('social-frontend-fake')
            ->expectsOutputToContain('Skipped src/routes/(public)/_guest/login/-components/google-login-button.tsx')
            ->expectsOutputToContain('Skipped AUTH-SOCIAL-FRONTEND-TODO.md')
            ->assertSuccessful();

        expect(file_get_contents($this->root . '/src/services/auth/social/api.ts'))->toBe('export {};' . PHP_EOL)
            ->and(
                file_get_contents($this->root . '/src/routes/(public)/_guest/login/-components/google-login-button.tsx')
            )
            ->toBe($before);
    });

    it(
        'signs in through the shared api after ensureCsrf, with no second HTTP client, token or storage',
        function (): void {
            $this->artisan('social-frontend-fake')->assertSuccessful();

            $api = (string) file_get_contents($this->root . '/src/services/auth/social/api.ts');

            expect($api)->toContain('import { api, ensureCsrf } from "@/config/api";')
                ->and(strpos($api, 'await ensureCsrf();'))->toBeLessThan(
                    strpos($api, 'api.post(`auth/social/${provider}`')
                );

            foreach ($this->sourceFiles as $relative) {
                expect(file_get_contents($this->root . '/' . $relative))
                    ->not->toContain('axios.create')
                    ->not->toContain('Bearer')
                    ->not->toContain('accessToken')
                    ->not->toContain('persistSession')
                    ->not->toContain('localStorage');
            }
        }
    );

    it('writes no comments into the generated TypeScript', function (): void {
        $this->artisan('social-frontend-fake')->assertSuccessful();

        foreach ($this->sourceFiles as $relative) {
            expect(file_get_contents($this->root . '/' . $relative))
                ->not->toMatch('#^\s*//#m')
                ->not->toContain('/*')
                ->not->toContain('eslint-disable');
        }
    });

    it('loads Google Identity Services from Google and shows the documented error when it cannot', function (): void {
        $this->artisan('social-frontend-fake')->assertSuccessful();

        $loader = (string) file_get_contents($this->root . '/src/services/auth/social/google-identity.ts');
        $button = (string) file_get_contents(
            $this->root . '/src/routes/(public)/_guest/login/-components/google-login-button.tsx'
        );

        expect($loader)
            ->toContain('"https://accounts.google.com/gsi/client"')
            ->and($button)
            ->toContain('<ErrorMessage errorMessage={t("socialLogin.googleUnavailable")} />')
            ->toContain('env.VITE_GOOGLE_CLIENT_ID')
            ->toContain('navigate(redirectTarget(search.redirect))');
    });

    it('documents every socialLogin.* key the generated files translate, with English copy', function (): void {
        $this->artisan('social-frontend-fake')->assertSuccessful();

        $documented = ($this->documentedKeys)();

        $used = [];
        foreach ($this->sourceFiles as $relative) {
            preg_match_all(
                '/\bt\("(socialLogin\.[a-zA-Z.]+)"/',
                (string) file_get_contents($this->root . '/' . $relative),
                $keys
            );
            $used = [...$used, ...$keys[1]];
        }

        expect($used)->not->toBeEmpty();

        foreach (array_unique($used) as $key) {
            expect(Arr::get($documented, $key))->toBeString()->not->toBeEmpty();
        }
    });

    it('maps every backend error code the button explains to a documented message', function (): void {
        $this->artisan('social-frontend-fake')->assertSuccessful();

        $types = (string) file_get_contents($this->root . '/src/services/auth/social/types.ts');

        expect($types)
            ->toContain('invalid_social_token: "invalidToken"')
            ->toContain('social_email_not_verified: "emailNotVerified"')
            ->toContain('social_provider_unavailable: "providerUnavailable"')
            ->and(array_keys(($this->documentedKeys)()['socialLogin']['errors']))
            ->toBe(['invalidToken', 'emailNotVerified', 'providerUnavailable']);
    });

    it('prints the client id, login form and i18n steps the TODO documents', function (): void {
        $this->artisan('social-frontend-fake')
            ->expectsOutputToContain('Manual step: set the Google client id (the backend\'s GOOGLE_CLIENT_ID).')
            ->expectsOutputToContain('VITE_GOOGLE_CLIENT_ID: z.string().min(1),')
            ->expectsOutputToContain('Manual step: add the "Sign in with Google" button to the login form.')
            ->expectsOutputToContain('import { GoogleLoginButton } from "./google-login-button";')
            ->expectsOutputToContain('<GoogleLoginButton />')
            ->expectsOutputToContain(
                'Manual step: add the socialLogin i18n block listed in AUTH-SOCIAL-FRONTEND-TODO.md'
            )
            ->assertSuccessful();

        expect(file_get_contents($this->root . '/AUTH-SOCIAL-FRONTEND-TODO.md'))
            ->toContain('`VITE_GOOGLE_CLIENT_ID: z.string().min(1),`')
            ->toContain('import { GoogleLoginButton } from "./google-login-button";')
            ->toContain('<GoogleLoginButton />')
            ->and(file_get_contents(
                $this->root . '/src/routes/(public)/_guest/login/-components/google-login-button.tsx'
            ))
            ->toContain('export const GoogleLoginButton = ');
    });

    it('signs in with the user-only hook when the 2FA frontend is not there', function (): void {
        $this->artisan('social-frontend-fake')->assertSuccessful();

        expect(file_get_contents($this->root . '/src/routes/(public)/_guest/login/-hooks/use-sign-in-with-google.ts'))
            ->toContain('await signInWithSocialProvider("google", credential);')
            ->toContain('queryClient.refetchQueries({ queryKey: currentUserQuery.queryKey })')
            ->not->toContain('two-factor');
    });

    it('routes a 2FA challenge to the 2FA screens when the 2FA frontend is already there', function (): void {
        foreach ([
            'src/stores/use-two-factor-challenge-store.ts',
            'src/services/auth/two-factor/types.ts',
            'src/routes/(public)/_guest/two-factor/page.tsx',
            'src/routes/(public)/_guest/two-factor/setup/page.tsx',
        ] as $relative) {
            File::ensureDirectoryExists(\dirname($this->root . '/' . $relative));
            file_put_contents($this->root . '/' . $relative, 'export {};' . PHP_EOL);
        }

        $this->artisan('social-frontend-fake')->assertSuccessful();

        expect(file_get_contents($this->root . '/src/routes/(public)/_guest/login/-hooks/use-sign-in-with-google.ts'))
            ->toContain('from "@/services/auth/two-factor/types"')
            ->toContain('from "@/stores/use-two-factor-challenge-store"')
            ->toContain('return isTwoFactorChallenge(body) ? body : null;')
            ->toContain('startChallenge(challenge);')
            ->toContain('to: isSetupRequired(challenge) ? "/two-factor/setup" : "/two-factor"')
            ->toContain('queryClient.refetchQueries({ queryKey: currentUserQuery.queryKey })');
    });
});
