// Generated by the light-it auth package v0.0.0-test (GoogleSSO).

import { useMutation } from "@tanstack/react-query";

import type { UseMutationProps } from "@/services/types";
import { loginWithGoogle } from "./api";

export const useGoogleLogin = (props?: UseMutationProps<typeof loginWithGoogle>) => {
  return useMutation({ mutationFn: loginWithGoogle, ...props });
};
