// Generated by the light-it auth package v0.0.0-test (GoogleSSO).

export type GoogleLoginResponse = {
  accessToken: string;
  tokenType: string;
  expiresIn: number | null;
};

export type GoogleLoginPayload = {
  idToken: string;
};
