// Generated by the light-it auth package v0.0.0-test (LaravelPermissions).

export const PERMISSIONS = {
users: {
    list: 'users.list',
    get: 'users.get',
    create: 'users.create',
    delete: 'users.delete',
},
roles: {
    readRole: 'roles.read',
    assignRole: 'roles.assign',
},
permissions: {
    readPermission: 'permissions.read',
},
} as const;

type ValueOf<T> = T extends Record<string, unknown> ? T[keyof T] : never;

export type PermissionValue = ValueOf<ValueOf<typeof PERMISSIONS>>;
