// Generated by the light-it auth package v0.0.0-test (LaravelPermissions).

import type { QueryClient } from "@tanstack/react-query";
import { redirect } from "@tanstack/react-router";

import { currentUserQuery } from "@/services/auth/factories";
import type { PermissionValue } from "./constants";

export const ensurePermission = async (
  queryClient: QueryClient,
  required: PermissionValue | PermissionValue[],
): Promise<void> => {
  const currentUser = await queryClient.ensureQueryData(currentUserQuery());
  const permissions = currentUser?.permissions ?? [];
  const requiredList = Array.isArray(required) ? required : [required];
  const hasAccess = requiredList.every((permission) => permissions.includes(permission));

  if (!hasAccess) {
    throw redirect({ to: "/" });
  }
};
