// Generated by the light-it auth package v0.0.0-test (LaravelPermissions).

import { useQuery } from "@tanstack/react-query";

import { currentUserQuery } from "@/services/auth/factories";
import type { PermissionValue } from "./constants";

type MatchOptions = {
  matchAll?: boolean;
};

export const usePermissions = () => {
  const { data: currentUser } = useQuery(currentUserQuery());

  const hasPermission = (expected: PermissionValue | PermissionValue[], options?: MatchOptions): boolean => {
    const permissions = currentUser?.permissions ?? [];
    const expectedList = Array.isArray(expected) ? expected : [expected];

    return options?.matchAll
      ? expectedList.every((permission) => permissions.includes(permission))
      : expectedList.some((permission) => permissions.includes(permission));
  };

  return { hasPermission };
};
