<?php

declare(strict_types=1);

use Lightitlabs\Tools\OriginMarker;

describe('OriginMarker', function (): void {
    it('builds the full sentence, deriving the feature from the stub path', function (
        string $stubPath,
        string $expected,
    ): void {
        $marker = new OriginMarker('1.2.3');

        expect($marker->forStub($stubPath))->toBe($expected);
    })->with([
        'Sanctum' => [
            '/app/src/Stubs/Sanctum/Auth/Controllers/LoginController.stub',
            'Generated by the light-it auth package v1.2.3 (Sanctum).',
        ],
        'Shared' => [
            '/app/src/Stubs/Shared/Auth/Requests/LoginRequest.stub',
            'Generated by the light-it auth package v1.2.3 (Shared).',
        ],
        'Exceptions' => [
            '/app/src/Stubs/Exceptions/InvalidGoogleTokenException.stub',
            'Generated by the light-it auth package v1.2.3 (Exceptions).',
        ],
        'GoogleSSO' => [
            '/app/src/Stubs/GoogleSSO/Auth/Controllers/GoogleLoginController.stub',
            'Generated by the light-it auth package v1.2.3 (GoogleSSO).',
        ],
        'Google2FA' => [
            '/app/src/Stubs/Google2FA/Auth/TwoFactorAuthenticatable.stub',
            'Generated by the light-it auth package v1.2.3 (Google2FA).',
        ],
        'Otp' => [
            '/app/src/Stubs/Otp/Auth/Controllers/OtpSendController.stub',
            'Generated by the light-it auth package v1.2.3 (Otp).',
        ],
        'ForgotPassword' => [
            '/app/src/Stubs/ForgotPassword/Auth/Controllers/ForgotPasswordController.stub',
            'Generated by the light-it auth package v1.2.3 (ForgotPassword).',
        ],
        'LaravelPermissions' => [
            '/app/src/Stubs/LaravelPermissions/Permissions/UserPermissions.stub',
            'Generated by the light-it auth package v1.2.3 (LaravelPermissions).',
        ],
        'Frontend' => [
            '/app/src/Stubs/Frontend/SanctumCookie/config/api.ts.stub',
            'Generated by the light-it auth package v1.2.3 (SanctumCookie).',
        ],
        'unmatched path' => [
            '/tmp/route-file-registrar-abc123/api.php',
            'Generated by the light-it auth package v1.2.3 (unknown).',
        ],
    ]);

    it('is constructed with resolved() from the real installed version', function (): void {
        $marker = OriginMarker::resolved();

        expect($marker->forStub('/app/src/Stubs/Sanctum/Auth/Controllers/LoginController.stub'))
            ->toStartWith('Generated by the light-it auth package v')
            ->toEndWith('(Sanctum).');
    });
});
