<?php

declare(strict_types=1);

use Lightitlabs\Tools\OriginMarker;
use Lightitlabs\Tools\StubCopier;
use Lightitlabs\Tools\StubCopyOutcome;

describe('StubCopier', function (): void {
    beforeEach(function (): void {
        $this->directory = sys_get_temp_dir().'/stub-copier-'.uniqid();
        mkdir($this->directory, 0755, true);
        $this->copier = new StubCopier(new OriginMarker('9.9.9'));
    });

    afterEach(function (): void {
        array_map('unlink', glob($this->directory.'/*') ?: []);
        rmdir($this->directory);
    });

    it('splices the marker in after the <?php header of a class stub', function (): void {
        $source = $this->directory.'/LoginController.stub';
        $destination = $this->directory.'/LoginController.php';

        file_put_contents(
            $source,
            "<?php\n\ndeclare(strict_types=1);\n\nnamespace App;\n\nfinal class LoginController\n{\n}\n"
        );

        $this->copier->copy($source, $destination);

        expect((string) file_get_contents($destination))->toBe(
            "<?php\n"
            ."// Generated by the light-it auth package v9.9.9 (unknown).\n"
            ."\ndeclare(strict_types=1);\n\nnamespace App;\n\nfinal class LoginController\n{\n}\n"
        );
    });

    it('splices the marker in after the <?php header of a lang file with no declare line', function (): void {
        $source = $this->directory.'/google2fa.stub';
        $destination = $this->directory.'/google2fa.php';

        file_put_contents($source, "<?php\n\nreturn [\n    'invalid_code' => 'Invalid code.',\n];\n");

        $this->copier->copy($source, $destination);

        expect((string) file_get_contents($destination))->toBe(
            "<?php\n"
            ."// Generated by the light-it auth package v9.9.9 (unknown).\n"
            ."\nreturn [\n    'invalid_code' => 'Invalid code.',\n];\n"
        );
    });

    it('splices the marker in right after a bare <?php tag with no blank line following', function (): void {
        $source = $this->directory.'/Bare.stub';
        $destination = $this->directory.'/Bare.php';

        file_put_contents($source, "<?php\nfinal class Bare\n{\n}\n");

        $this->copier->copy($source, $destination);
        $result = (string) file_get_contents($destination);

        expect($result)->toBe(
            "<?php\n"
            ."// Generated by the light-it auth package v9.9.9 (unknown).\n"
            ."final class Bare\n{\n}\n"
        );
    });

    it('splices the marker in after a <?php tag immediately followed by a return statement', function (): void {
        $source = $this->directory.'/InlineReturn.stub';
        $destination = $this->directory.'/InlineReturn.php';

        file_put_contents($source, "<?php return ['key' => 'value'];\n");

        $this->copier->copy($source, $destination);
        $result = (string) file_get_contents($destination);

        expect($result)->toStartWith("<?php return ['key' => 'value'];\n")
            ->and($result)->toContain("\n// Generated by the light-it auth package v9.9.9 (unknown).\n");
    });

    it('splices the marker in after a <?php tag immediately followed by a declare statement', function (): void {
        $source = $this->directory.'/InlineDeclare.stub';
        $destination = $this->directory.'/InlineDeclare.php';

        file_put_contents($source, "<?php declare(strict_types=1);\n\nfinal class InlineDeclare\n{\n}\n");

        $this->copier->copy($source, $destination);
        $result = (string) file_get_contents($destination);

        expect($result)->toBe(
            "<?php declare(strict_types=1);\n"
            ."// Generated by the light-it auth package v9.9.9 (unknown).\n"
            ."\nfinal class InlineDeclare\n{\n}\n"
        );
    });

    it('never overwrites an existing destination file on a second copy() run', function (): void {
        $source = $this->directory.'/LoginController.stub';
        $destination = $this->directory.'/LoginController.php';

        file_put_contents($source, "<?php\n\ndeclare(strict_types=1);\n\nfinal class LoginController\n{\n}\n");

        $first = $this->copier->copy($source, $destination);
        $contentAfterFirstRun = (string) file_get_contents($destination);

        $second = $this->copier->copy($source, $destination);
        $contentAfterSecondRun = (string) file_get_contents($destination);

        expect($first)->toBe(StubCopyOutcome::Written);
        expect($second)->toBe(StubCopyOutcome::Skipped);
        expect($contentAfterSecondRun)->toBe($contentAfterFirstRun);
        expect(substr_count($contentAfterSecondRun, 'Generated by the light-it auth package'))->toBe(1);
    });

    it('throws when the source stub cannot be read', function (): void {
        $missing = $this->directory.'/missing.stub';
        $destination = $this->directory.'/missing.php';

        expect(fn () => $this->copier->copy($missing, $destination))
            ->toThrow(RuntimeException::class, "Unable to read stub: {$missing}");
    });

    it('throws when the destination cannot be written', function (): void {
        $source = $this->directory.'/LoginController.stub';
        $destination = $this->directory.'/does-not-exist/LoginController.php';

        file_put_contents($source, "<?php\n\ndeclare(strict_types=1);\n");

        expect(fn () => $this->copier->copy($source, $destination))
            ->toThrow(RuntimeException::class, "Unable to write file: {$destination}");
    });
});
