<?php

declare(strict_types=1);

use Lightitlabs\Tools\OriginMarker;
use Lightitlabs\Tools\StubCopier;

describe('StubCopier', function (): void {
    beforeEach(function (): void {
        $this->directory = sys_get_temp_dir().'/stub-copier-'.uniqid();
        mkdir($this->directory, 0755, true);
        $this->copier = new StubCopier(new OriginMarker('9.9.9'));
    });

    afterEach(function (): void {
        array_map('unlink', glob($this->directory.'/*') ?: []);
        rmdir($this->directory);
    });

    it('splices the marker in after the <?php header of a class stub', function (): void {
        $source = $this->directory.'/LoginController.stub';
        $destination = $this->directory.'/LoginController.php';

        file_put_contents(
            $source,
            "<?php\n\ndeclare(strict_types=1);\n\nnamespace App;\n\nfinal class LoginController\n{\n}\n"
        );

        $this->copier->copy($source, $destination);

        expect((string) file_get_contents($destination))->toBe(
            "<?php\n\n"
            ."// Generated by the light-it auth package v9.9.9 (unknown).\n\n"
            ."declare(strict_types=1);\n\nnamespace App;\n\nfinal class LoginController\n{\n}\n"
        );
    });

    it('splices the marker in after the <?php header of a lang file with no declare line', function (): void {
        $source = $this->directory.'/google2fa.stub';
        $destination = $this->directory.'/google2fa.php';

        file_put_contents($source, "<?php\n\nreturn [\n    'invalid_code' => 'Invalid code.',\n];\n");

        $this->copier->copy($source, $destination);

        expect((string) file_get_contents($destination))->toBe(
            "<?php\n\n"
            ."// Generated by the light-it auth package v9.9.9 (unknown).\n\n"
            ."return [\n    'invalid_code' => 'Invalid code.',\n];\n"
        );
    });

    it('does not stack a second marker when copy() runs twice into the same destination', function (): void {
        $source = $this->directory.'/LoginController.stub';
        $destination = $this->directory.'/LoginController.php';

        file_put_contents($source, "<?php\n\ndeclare(strict_types=1);\n\nfinal class LoginController\n{\n}\n");

        $this->copier->copy($source, $destination);
        $this->copier->copy($source, $destination);

        $finalContent = (string) file_get_contents($destination);

        expect(substr_count($finalContent, 'Generated by the light-it auth package'))->toBe(1);
    });

    it('throws when the source stub cannot be read', function (): void {
        $missing = $this->directory.'/missing.stub';
        $destination = $this->directory.'/missing.php';

        expect(fn () => $this->copier->copy($missing, $destination))
            ->toThrow(RuntimeException::class, "Unable to read stub: {$missing}");
    });

    it('throws when the destination cannot be written', function (): void {
        $source = $this->directory.'/LoginController.stub';
        $destination = $this->directory.'/does-not-exist/LoginController.php';

        file_put_contents($source, "<?php\n\ndeclare(strict_types=1);\n");

        expect(fn () => $this->copier->copy($source, $destination))
            ->toThrow(RuntimeException::class, "Unable to write file: {$destination}");
    });
});
