<?php

declare(strict_types=1);

namespace Lightitlabs\Tools;

/**
 * Installs 2FA's pipeline `LoginAction.php` over Sanctum's plain one without a
 * blind overwrite. Both versions are entirely package-generated - unlike the
 * consumer-authored file `PhpResourcePatcher` patches - so there is nothing to
 * merge line-by-line. The risk `PhpResourcePatcher` guards against still
 * applies, though: `/auth-add-feature` can install 2FA onto an app that has
 * been running with Sanctum's plain `LoginAction.php` for a while, and a
 * consumer may have edited it by hand in the meantime. Replacing it is only
 * safe when it still matches this package's own unmodified output.
 */
final class LoginActionPatcher
{
    private const ORIGIN_MARKER_PATTERN = '/^<\?php\n\n\/\/ Generated by the light-it auth package v[^\n]*\n\n/';

    public function install(
        StubCopier $stubCopier,
        string $plainStubPath,
        string $pipelineStubPath,
        string $destination,
    ): LoginActionPatchOutcome {
        $pipelineStub = @file_get_contents($pipelineStubPath);

        if ($pipelineStub === false) {
            return LoginActionPatchOutcome::SourceMissing;
        }

        if (! file_exists($destination)) {
            $stubCopier->copy($pipelineStubPath, $destination);

            return LoginActionPatchOutcome::Installed;
        }

        $current = @file_get_contents($destination);

        if ($current === false) {
            return LoginActionPatchOutcome::Failed;
        }

        $normalizedCurrent = $this->stripOriginMarker($current);

        if ($normalizedCurrent === $pipelineStub) {
            return LoginActionPatchOutcome::AlreadyApplied;
        }

        $plainStub = @file_get_contents($plainStubPath);

        if ($plainStub === false) {
            return LoginActionPatchOutcome::SourceMissing;
        }

        if ($normalizedCurrent !== $plainStub) {
            return LoginActionPatchOutcome::CustomizedSkipped;
        }

        $stubCopier->copy($pipelineStubPath, $destination);

        return LoginActionPatchOutcome::Patched;
    }

    /**
     * Strips the `// Generated by the light-it auth package v...` line
     * `StubCopier::copy()` stamps onto every file it writes, so a destination
     * can be compared against a raw, unstamped stub regardless of which
     * package version wrote it.
     */
    private function stripOriginMarker(string $contents): string
    {
        return (string) preg_replace(self::ORIGIN_MARKER_PATTERN, "<?php\n\n", $contents, 1);
    }
}
