<?php

declare(strict_types=1);

namespace Lightitlabs\Tools;

final class OriginMarker
{
    private const FRONTEND_FEATURE_PATTERN = '#/Stubs/Frontend/([^/]+)/#';

    private const BACKEND_FEATURE_PATTERN = '#/Stubs/([^/]+)/#';

    public function __construct(private readonly string $version) {}

    public static function resolved(): self
    {
        return new self((new PackageVersion)->resolve());
    }

    public function forStub(string $stubPath): string
    {
        $feature = $this->featureFor($stubPath);

        return "Generated by the light-it auth package v{$this->version} ({$feature}).";
    }

    private function featureFor(string $stubPath): string
    {
        if (preg_match(self::FRONTEND_FEATURE_PATTERN, $stubPath, $matches) === 1) {
            return $matches[1];
        }

        if (preg_match(self::BACKEND_FEATURE_PATTERN, $stubPath, $matches) === 1) {
            return $matches[1];
        }

        return 'unknown';
    }
}
